/**
 * @fileoverview Constants exports.
 * @module constants
 */

export {
  MODULE_METADATA,
  GLOBAL_MODULE_METADATA,
  INJECTABLE_WATERMARK,
  SCOPE_OPTIONS_METADATA,
  PARAMTYPES_METADATA,
  SELF_DECLARED_DEPS_METADATA,
  OPTIONAL_DEPS_METADATA,
  PROPERTY_DEPS_METADATA,
  OPTIONAL_PROPERTY_DEPS_METADATA,
} from './tokens.constant';
